package org.the_chance.honeymart.ui.features.category.composable

import org.the_chance.design_system.R

val categoryIcons = mapOf(
    1 to R.drawable.cart,
    2 to R.drawable.ic_star_fall_minimalistic,
    3 to R.drawable.ic_pallete_2,
    4 to R.drawable.ic_ruler_pen,
    5 to R.drawable.airbuds,
    6 to R.drawable.airbuds_case_open,
    7 to R.drawable.display,
    8 to R.drawable.flash_drive,
    9 to R.drawable.gameboy,
    10 to R.drawable.gamepad,
    11 to R.drawable.headphones_round,
    12 to R.drawable.keyboard,
    13 to R.drawable.bag_smile,
    14 to R.drawable.laptop_3,
    15 to R.drawable.lightbulb_bolt,
    16 to R.drawable.cat,
    17 to R.drawable.cosmetic,
    18 to R.drawable.flashlight,
    19 to R.drawable.gift,
    20 to R.drawable.glasses,
    21 to R.drawable.hanger_3,
    22 to R.drawable.mirror,
    23 to R.drawable.perfume,
    24 to R.drawable.skirt,
    25 to R.drawable.t_shirt,
    26 to R.drawable.perfume,
    27 to R.drawable.bottle,
    28 to R.drawable.cup_paper,
    29 to R.drawable.donut_bitten,
    30 to R.drawable.tea_cup,
    31 to R.drawable.lamp,
    32 to R.drawable.sofa,
    33 to R.drawable.medical_kit,
    34 to R.drawable.notebook,
    35 to R.drawable.dumbbell_large,
)