package org.the_chance.honeymart.domain.util

/**
 * Created by Aziza Helmy on 6/16/2023.
 */
enum class ValidationState {
    BLANK_EMAIL,
    INVALID_EMAIL,
    VALID_EMAIL,

    INVALID_MARKET_NAME,
    VALID_MARKET_NAME,
    BLANK_MARKET_NAME,

    BLANK_MARKET_ADDRESS,
    VALID_MARKET_ADDRESS,

    BLANK_MARKET_DESCRIPTION,
    SHORT_MARKET_DESCRIPTION,
    VALID_MARKET_DESCRIPTION,

    BLANK_PASSWORD,
    INVALID_PASSWORD,
    INVALID_PASSWORD_LENGTH,
    INVALID_CONFIRM_PASSWORD,
    PASSWORD_REGEX_ERROR_LETTER,
    PASSWORD_REGEX_ERROR_DIGIT,
    PASSWORD_REGEX_ERROR_SPECIAL_CHARACTER,
    VALID_PASSWORD,

    BLANK_FULL_NAME,
    INVALID_FULL_NAME,
    VALID_FULL_NAME,
    SUCCESS,
    BLANK_TEXT_FIELD,
    VALID_TEXT_FIELD,
    SHORT_LENGTH_TEXT,
    INVALID_PRICE
}